[package]
name = "dso-dojo-2023-01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r2d2_redis = "0.14.0"
lazy_static = "1.4.0"

[dependencies.rocket]
version = "0.5.0-rc.2"
features = ["json"]
