version: "3.1"
services:
  postgres:
    image: postgres
    command: postgres -c 'max_connections=20000'
    restart: always
    environment:
      POSTGRES_PASSWORD: plaintext
    network_mode: host
  dso_dojo_slow_postgres:
    image: thecjharries/dso_dojo_slow_postgres
    environment:
      ROCKET_DATABASES: '{postgres={url="postgres://postgres:plaintext@localhost:5432/postgres"}}'
      ROCKET_PORT: 8001
      API_WAIT_SECONDS: 10
    network_mode: host
  redis:
    image: redis
    restart: always
    network_mode: host
