version: "3.1"
services:
  reverseproxy:
    image: thecjharries/dso-dojo-2023-01-reverseproxy
    ports:
      - "80:80"
    depends_on:
      - dso_dojo_slow_postgres
      - cacheserver
    networks:
      network:
        ipv4_address: 10.0.0.1
  postgres:
    image: postgres
    command: postgres -c 'max_connections=20000'
    restart: always
    environment:
      POSTGRES_PASSWORD: plaintext
    ports:
      - "5432:5432"
    networks:
      network:
        ipv4_address: 10.0.0.2
  dso_dojo_slow_postgres:
    image: thecjharries/dso_dojo_slow_postgres
    environment:
      ROCKET_DATABASES: '{postgres={url="postgres://postgres:plaintext@10.0.0.2:5432/postgres"}}'
      ROCKET_PORT: 8000
      API_WAIT_SECONDS: 10
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      network:
        ipv4_address: 10.0.0.3
  cacheserver:
    image: thecjharries/dso-dojo-2023-01-cacheserver
    environment:
      ROCKET_PORT: 8001
      REDIS_CONNECTION_STRING: "redis://10.0.0.5:6379"
      API_ROOT: "http://10.0.0.3:8000"
    ports:
      - "8001:8001"
    depends_on:
      - dso_dojo_slow_postgres
      - redis
    restart: always
    networks:
      network:
        ipv4_address: 10.0.0.4
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      network:
        ipv4_address: 10.0.0.5

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.254
