name: Test

on:
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the exercise
        uses: actions/checkout@v3
        with:
          repository: thecjharries/dso-dojo-slow-server
          path: ./dso-dojo-slow-server

      - name: Build dependencies
        run: make docker-build
        working-directory: ./dso-dojo-slow-server

      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache cargo deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Start the dev stack
        run: make dev

      - name: Test the server
        run: cargo test --verbose

      - name: Stop the dev stack
        if: always()
        run: make dev
